class FlagCodeSet:
    def __init__(self):
        self.BTN_MISC = 0x100
        self.BTN_0 = 0x100
        self.BTN_1 = 0x101
        self.BTN_2 = 0x102
        self.BTN_3 = 0x103
        self.BTN_4 = 0x104
        self.BTN_5 = 0x105
        self.BTN_6 = 0x106
        self.BTN_7 = 0x107
        self.BTN_8 = 0x108
        self.BTN_9 = 0x109
        self.BTN_MOUSE = 0x110
        self.BTN_LEFT = 0x110
        self.BTN_RIGHT = 0x111
        self.BTN_MIDDLE = 0x112
        self.BTN_SIDE = 0x113
        self.BTN_EXTRA = 0x114
        self.BTN_FORWARD = 0x115
        self.BTN_BACK = 0x116
        self.BTN_TASK = 0x117
        self.BTN_JOYSTICK = 0x120
        self.BTN_TRIGGER = 0x120
        self.BTN_THUMB = 0x121
        self.BTN_THUMB2 = 0x122
        self.BTN_TOP = 0x123
        self.BTN_TOP2 = 0x124
        self.BTN_PINKIE = 0x125
        self.BTN_BASE = 0x126
        self.BTN_BASE2 = 0x127
        self.BTN_BASE3 = 0x128
        self.BTN_BASE4 = 0x129
        self.BTN_BASE5 = 0x12a
        self.BTN_BASE6 = 0x12b
        self.BTN_DEAD = 0x12f
        self.BTN_GAMEPAD = 0x130
        self.BTN_SOUTH = 0x130
        self.BTN_EAST = 0x131
        self.BTN_C = 0x132
        self.BTN_NORTH = 0x133
        self.BTN_WEST = 0x134
        self.BTN_Z = 0x135
        self.BTN_TL = 0x136
        self.BTN_TR = 0x137
        self.BTN_TL2 = 0x138
        self.BTN_TR2 = 0x139
        self.BTN_SELECT = 0x13a
        self.BTN_START = 0x13b
        self.BTN_MODE = 0x13c
        self.BTN_THUMBL = 0x13d
        self.BTN_THUMBR = 0x13e
        self.BTN_DIGI = 0x140
        self.BTN_TOOL_PEN = 0x140
        self.BTN_TOOL_RUBBER = 0x141
        self.BTN_TOOL_BRUSH = 0x142
        self.BTN_TOOL_PENCIL = 0x143
        self.BTN_TOOL_AIRBRUSH = 0x144
        self.BTN_TOOL_FINGER = 0x145
        self.BTN_TOOL_MOUSE = 0x146
        self.BTN_TOOL_LENS = 0x147
        self.BTN_TOOL_QUINTTAP = 0x148  # Five fingers on trackpad
        self.BTN_TOUCH = 0x14a
        self.BTN_STYLUS = 0x14b
        self.BTN_STYLUS2 = 0x14c
        self.BTN_TOOL_DOUBLETAP = 0x14d
        self.BTN_TOOL_TRIPLETAP = 0x14e
        self.BTN_TOOL_QUADTAP = 0x14f  # Four fingers on trackpad
        self.BTN_WHEEL = 0x150
        self.BTN_GEAR_DOWN = 0x150
        self.BTN_GEAR_UP = 0x151
        self.BTN_DPAD_UP = 0x220
        self.BTN_DPAD_DOWN = 0x221
        self.BTN_DPAD_LEFT = 0x222
        self.BTN_DPAD_RIGHT = 0x223

class AxisCodeSet:
    def __init__(self):
        self.ABS_X = 0x00
        self.ABS_Y = 0x01
        self.ABS_Z = 0x02
        self.ABS_RX = 0x03
        self.ABS_RY = 0x04
        self.ABS_RZ = 0x05
        self.ABS_THROTTLE = 0x06
        self.ABS_RUDDER = 0x07
        self.ABS_WHEEL = 0x08
        self.ABS_GAS = 0x09
        self.ABS_BRAKE = 0x0a
        self.ABS_HAT0X = 0x10
        self.ABS_HAT0Y = 0x11
        self.ABS_HAT1X = 0x12
        self.ABS_HAT1Y = 0x13
        self.ABS_HAT2X = 0x14
        self.ABS_HAT2Y = 0x15
        self.ABS_HAT3X = 0x16
        self.ABS_HAT3Y = 0x17
        self.ABS_PRESSURE = 0x18
        self.ABS_DISTANCE = 0x19
        self.ABS_TILT_X = 0x1a
        self.ABS_TILT_Y = 0x1b
        self.ABS_TOOL_WIDTH = 0x1c
        self.ABS_VOLUME = 0x20
        self.ABS_MISC = 0x28
        self.ABS_MT_SLOT = 0x2f  # MT slot being modified
        self.ABS_MT_TOUCH_MAJOR = 0x30  # Major self of touching ellipse
        self.ABS_MT_TOUCH_MINOR = 0x31  # Minor self (omit if circular)
        self.ABS_MT_WIDTH_MAJOR = 0x32  # Major self of approaching ellipse
        self.ABS_MT_WIDTH_MINOR = 0x33  # Minor self (omit if circular)
        self.ABS_MT_ORIENTATION = 0x34  # Ellipse orientation
        self.ABS_MT_POSITION_X = 0x35  # Center X touch position
        self.ABS_MT_POSITION_Y = 0x36  # Center Y touch position
        self.ABS_MT_TOOL_TYPE = 0x37  # Type of touching device
        self.ABS_MT_BLOB_ID = 0x38  # Group a set of packets as a blob
        self.ABS_MT_TRACKING_ID = 0x39  # Unique ID of initiated contact
        self.ABS_MT_PRESSURE = 0x3a  # Pressure on contact area
        self.ABS_MT_DISTANCE = 0x3b  # Contact hover distance
        self.ABS_MT_TOOL_X = 0x3c  # Center X tool position
        self.ABS_MT_TOOL_Y = 0x3d  # Center Y tool position
        self.ABS_MAX = 0x3f

class CodeSet:
    def __init__(self):
        self.flag = FlagCodeSet()
        self.axis = AxisCodeSet()

codes = CodeSet()